### PR TITLE
fix a wave-dash glyph

### PR DESCRIPTION
**Pull request by kkdd**

### CODE REVIEW

**Comment by equal-l2** [comment]
What is this PR do?

Could you tell us the change visually (e.g. picture)?

You can attach files to comment.

**Comment by kkdd** [comment]
A correct Unicode wave-dash (U+301C) glyph is not https://ja.wikipedia.org/wiki/File:Wave_Dash2.svg but https://ja.wikipedia.org/wiki/File:Wave_Dash.svg. See also https://en.wikipedia.org/wiki/Wave_dash.

**Comment by equal-l2** [comment]
I couldn't reproduce the problem with either Ricty or Migu-1M.

This issue is 2 years old now, so Migu-1M may be updated.

**Comment by equal-l2** [comment]
Look here. (Written in Japanese)
https://osdn.net/projects/mix-mplus-ipa/forums/9259/30313/76515/

The problem seems fixed.
Do you still reproduce the problem?

**Comment by kkdd** [comment]
Thank you for checking the latest information of Migu-1M. Now, yes, you are right and the version '20150712' have corrected the wave-dash glyph according to Unicode 8.0 (2015). This PR should be closed.

**Pull request closed without merging**
